config/routes.rb
Rails.application.routes.draw do
  resources :subcontractors do
    collection do
      get 'list'
    end
  end
  root :to => 'application#application'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :services do
    collection do
      get 'list'
    end
  end
  resources :brands
  resources :districts
  resources :payment_types
  resources :device_types
  resources :create_device_types
  resources :data do
    collection do
      get 'service_list'
      get 'customer_list'
    end
  end

  resources :customers do
    collection do
      get 'list'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subcontractor.rb
# == Schema Information
#
# Table name: subcontractors
#
#  id          :bigint           not null, primary key
#  credit      :float
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  service_id  :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_subcontractors_on_service_id  (service_id)
#  index_subcontractors_on_user_id     (user_id)
#
class Subcontractor < ApplicationRecord
  has_many :services
  belongs_to :user

  before_destroy :can_destroy?

  after_initialize do |subcontractor|
    subcontractor.user = User.current
  end

  private

  def can_destroy?
    if self.services.count > 0
      self.errors.add(:base, "Bu taşerona verilmiş servisler olduğu için silemezsiniz.")
      throw :abort
    end
  end

end

app/controllers/subcontractors_controller.rb
class SubcontractorsController < ApplicationController
  before_action :set_subcontractors, only: [:index, :list, :show, :edit, :update, :destroy]

  # GET /subcontractors
  # GET /subcontractors.json
  def index
    @subcontractors = Subcontractor.all
  end

  # GET /subcontractors/1
  # GET /subcontractors/1.json
  def show
    @deletable = "Taşeronu Sil"
    render_modal "Taşeron Düzenleme"
  end

  # GET /subcontractors/new
  def new
    @subcontractor = Subcontractor.new
    render_modal "Taşeron Ekleme"
  end

  # GET /subcontractors/1/edit
  def edit
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcontractors
      @subcontractors = current_user.subcontractors.order(created_at: :asc)
      @subcontractor = Subcontractor.find(params[:id]) rescue nil
    end

    # Only allow a list of trusted parameters through.
    def subcontractor_params
      params.fetch(:subcontractor, {}).permit(:name, :credit, :description)
    end
end

app/helpers/subcontractors_helper.rb
module SubcontractorsHelper
end

app/views/subcontractors/_form.html.erb
<%= simple_form_for @object, remote: true, html: { id: dom_id(@object, params[:action]) } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="field">
    <div class="two fields">
      <%= f.input :name, label: 'Taşeron ismi', placeholder: 'Taşeronun adı', input_html: { class: 'ui selection dropdown field search' }, wrapper_html: { class: 'field' } %>
      <%= f.input :credit, label: 'Varolan hesap/Alacak verecek', placeholder: 'Taşeron ile aranızda herhangi bir alacak/verecek varsa buraya yazınız', input_html: { class: 'ui selection dropdown field search' }, wrapper_html: { class: 'field' } %>
    </div>
  </div>

  <div class="field">
    <div class="two fields">
      <%= f.input :description, as: :text, label: 'Taşeron Notu', placeholder: "Taşeron ile ilgili açıklama", input_html: { class: "field", rows: "2" }, wrapper_html: {class: 'field'} %>
    </div>
  </div>
<% end %>

app/views/subcontractors/_new.html.erb
<%= render 'form', subcontractor: @subcontractor %>

app/views/subcontractors/_show.html.erb
<%= render partial: 'subcontractors/form' %>

app/views/subcontractors/edit.html.erb
<h1>Editing Subcontractor</h1>

<%= render 'form', subcontractor: @subcontractor %>

<%= link_to 'Show', @subcontractor %> |
<%= link_to 'Back', subcontractors_path %>

app/views/subcontractors/index.html.erb
<% if notice.present? %>
  <script>
      <%= render partial: "/shared/toasts/show_toast", formats: :js %>
  </script>
<% end %>

<h1>Taşeronlar</h1>

<div id="subcontractor_list" class="ui form">
  <%= render partial: 'subcontractors/partials/subcontractor_list' %>
</div>

app/views/subcontractors/list.js.erb
$("#subcontractor_list").html("");
$("#subcontractor_list").html(`<%= render partial: "subcontractors/partials/subcontractor_list" %>`);
$("#subcontractor_list").removeClass("loading")