config/routes.rb
Rails.application.routes.draw do
  resources :subcontractors do
    collection do
      get 'list'
    end
  end
  root :to => 'application#application'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :services do
    collection do
      get 'list'
    end
  end
  resources :brands
  resources :districts
  resources :payment_types
  resources :device_types
  resources :create_device_types
  resources :data do
    collection do
      get 'service_list'
      get 'customer_list'
    end
  end

  resources :customers do
    collection do
      get 'list'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subcontractor.rb
# == Schema Information
#
# Table name: subcontractors
#
#  id          :bigint           not null, primary key
#  credit      :float
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  service_id  :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_subcontractors_on_service_id  (service_id)
#  index_subcontractors_on_user_id     (user_id)
#
class Subcontractor < ApplicationRecord
  has_many :services
  belongs_to :user

  before_destroy :can_destroy?

  after_initialize do |subcontractor|
    subcontractor.user = User.current
  end

  private

  def can_destroy?
    if self.services.count > 0
      self.errors.add(:base, "Bu taşerona verilmiş servisler olduğu için silemezsiniz.")
      throw :abort
    end
  end

end

app/controllers/subcontractors_controller.rb
class SubcontractorsController < ApplicationController
  before_action :set_subcontractors, only: [:index, :list, :show, :edit, :update, :destroy]

  # GET /subcontractors
  # GET /subcontractors.json
  def index
    @subcontractors = Subcontractor.all
  end

  # GET /subcontractors/1
  # GET /subcontractors/1.json
  def show
    @deletable = "Taşeronu Sil"
    render_modal "Taşeron Düzenleme"
  end

  # GET /subcontractors/new
  def new
    @subcontractor = Subcontractor.new
    render_modal "Taşeron Ekleme"
  end

  # GET /subcontractors/1/edit
  def edit
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcontractors
      @subcontractors = current_user.subcontractors.order(created_at: :asc)
      @subcontractor = Subcontractor.find(params[:id]) rescue nil
    end

    # Only allow a list of trusted parameters through.
    def subcontractor_params
      params.fetch(:subcontractor, {}).permit(:name, :credit, :description)
    end
end

app/helpers/subcontractors_helper.rb
module SubcontractorsHelper
end

app/views/subcontractors/partials/_subcontractor_list.erb
<table class="ui celled table" id="subcontractor_table">
  <thead>
  <tr>
    <th>İsim</th>
    <th>Kredi</th>
    <th>Açıklama</th>
  </tr>
  </thead>

  <tbody>
  <% @subcontractors.each do |subcontractor| %>
    <tr>
      <td><%= link_to subcontractor.name, subcontractor, remote: true %></td>
      <td><%= subcontractor.credit %></td>
      <td><%= subcontractor.description %></td>
    </tr>
  <% end %>
  </tbody>

  <tfoot class="full-width">
  <tr>
    <th colspan="5">
      <%= link_to new_subcontractor_path, remote: true, class: 'ui right floated small primary labeled icon button new_subcontractor' do %>
        <i class="plus icon"></i> Taşeron Ekle
      <% end %>
    </th>
  </tr>
  </tfoot>
</table>