config/routes.rb
Rails.application.routes.draw do
  resources :subcontractors do
    collection do
      get 'list'
    end
  end
  root :to => 'application#application'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :services do
    collection do
      get 'list'
    end
  end
  resources :brands
  resources :districts
  resources :payment_types
  resources :device_types
  resources :create_device_types
  resources :data do
    collection do
      get 'service_list'
      get 'customer_list'
    end
  end

  resources :customers do
    collection do
      get 'list'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id          :bigint           not null, primary key
#  address     :string
#  name        :string
#  phone       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  district_id :integer          not null
#  user_id     :integer          not null
#
class Customer < ApplicationRecord
  has_many :services
  belongs_to :district
  accepts_nested_attributes_for :services

  validates :name, presence: true
  validates :phone, presence: true
  validates :address, presence: true


  def self.default_scope
    where(user_id: User.current.id) if User.current.present?
  end

  after_initialize do |customer|
    customer.user_id = User.current.id if User.current.present?
  end

  def self.create_customer_or_service(params)
    customer = self.find_or_initialize_by(phone: params[:phone])
    if customer.new_record?
      self.new(params)
    else
      customer.services.new params[:services_attributes]["0"]
    end
  end

  def full_address
    (self.address + " " + self.district_name).gsub!("\\", "\\\\\\\\")
  end

  def district_name
    self.district[:discrict_name]
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :customer_list, only: [:index, :list, :create]

  def index
    @customers = Customer.all
  end

  def show
    render_modal "Müşteri Detayı"
  end

  def edit
    @customer_services = @customers.services
    render_modal "Müşteri Detayı"
  end

  def new
    @customer = Customer.new
    render_modal "Müşteri Kayıt"
  end

  def create
    respond_to do |format|
      if @object.save
        format.js { render "create" }
      else
        format.js { render "errors" }
      end
    end
  end

  def update
    respond_to do |format|
      if @object.update(permit_params)
        flash[:success] = "Müşteri güncellendi"
        format.js { render "#{params[:action]}" }
        format.html { render "#{params[:action]}"}
      else
        format.js { render "errors" }
      end
    end
  end

  def list
    render "list"
  end


  private

  def customer_list
    @customers = current_user.customers.all
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def permit_params
      params.fetch(:customer, {}).permit(:name, :phone, :address, :district_id, services_attributes: [:address, :district_id, :device_type_id, :brand_id, :defect, :description, :appointment_date, :subcontractor_id])
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_edit.html.erb
<%= render 'form', customer: @customer %>
  <div class="ui styled accordion">
    <div class="title">
      <i class="dropdown icon"></i>
      Müşterinin Servisleri
    </div>
    <div class="content">
      <% @customer_services.each do |service| %>
        <ol class="ui suffixed list">
          <li><%= link_to service.display, service_path(service, multiple: true), remote: true, class: "item transition" %></li>
        </ol>
      <% end %>
    </div>
  </div>

  <script type="text/javascript" charset="utf-8">
      $('.ui.accordion').accordion();
  </script>

app/views/customers/_form.html.erb
<div class="ui form">
  <%= simple_form_for @customer, remote: true, authenticity_token: true, html: { id: dom_id(@customer, params[:action]) } do |customer| %>
  <%= customer.error_notification %>
  <%= customer.error_notification message: customer.object.errors[:base].to_sentence if customer.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="field">
      <div class="two fields">
        <%= customer.input :name, label: 'İsim Soyisim', placeholder: "İsim Soyisim", wrapper_html: { class: 'field' } %>
        <%= customer.input :phone, label: 'Telefon Numarası', placeholder: "Telefon Numarası", wrapper_html: { class: 'field' } %>
      </div>
    </div>
  </div>

  <div class="field">
    <div class="two fields">
      <%= customer.input :address, as: :text, label: 'Adres', required: true, placeholder: "Adres", input_html: { rows: "2", value: customer.object.address.gsub!("\\", "\\\\\\\\") }, wrapper_html: {class: 'eight wide field'} %>
      <%= customer.association :district, as: :select, label: 'Semt', :collection => District.all.map { |e| [e.discrict_name, e.id] }, input_html: { class: 'ui selection dropdown field search' }, wrapper_html: { class: 'field' }, include_blank: false %>
    </div>
  </div>
    <% if params[:from].present? %>
      <input type="hidden" name="from" value="<%= params[:from] %>">
      <input type="hidden" name="close_modal" value="<%= params[:close_modal] %>">
    <% end %>
<% end %>
</div>

app/views/customers/_new.html.erb
<%= render 'form', customer: @customer %>

app/views/customers/_show.html.erb
<%= render "form" %>

app/views/customers/create.js.erb
$("#customer_list").addClass("loading")
$.get("<%= list_customers_path %>")
<%= render partial: '/shared/modals/close_modal' %>

// Servis oluşturma sayfasından müşteri eklendiği zaman
// Servis modalında dropdown yenilenmediği için modalı yeniden yüklüyoruz.
<% if params[:from] == 'services_list' %>
  $(".ui.modal.<%= params[:close_modal] %>").modal('hide');
  $(".ui.modal.<%= params[:close_modal] %>").modal('hide dimmer');
  $("a.new_service")[0].click()
<% end %>

app/views/customers/errors.js.erb
<%= render partial: "shared/modals/show_modal_error", format: "js" %>

app/views/customers/index.html.erb
<%= render partial: "customers/partials/customer_list" %>

app/views/customers/list.js.erb
$("#customer_list").html("");
$("#customer_list").html(`<%= render "customers/partials/customer_list" %>`);
$("#customer_list").removeClass("loading")

app/views/customers/update.js.erb
<%= render partial: "/shared/toasts/show_toast", format: :js %>
$("#customer_list").addClass("loading")
$.get("<%= list_customers_path %>")
<%= render partial: '/shared/modals/close_modal' %>