config/routes.rb
Rails.application.routes.draw do
  resources :subcontractors do
    collection do
      get 'list'
    end
  end
  root :to => 'application#application'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :services do
    collection do
      get 'list'
    end
  end
  resources :brands
  resources :districts
  resources :payment_types
  resources :device_types
  resources :create_device_types
  resources :data do
    collection do
      get 'service_list'
      get 'customer_list'
    end
  end

  resources :customers do
    collection do
      get 'list'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id               :bigint           not null, primary key
#  address          :string
#  appointment_date :datetime
#  defect           :string
#  description      :string
#  mobile_phone     :string
#  name             :string
#  phone            :string
#  status           :string           default("0")
#  surname          :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  brand_id         :bigint           not null
#  customer_id      :integer          not null
#  device_type_id   :bigint           not null
#  subcontractor_id :integer
#  user_id          :bigint           not null
#
# Indexes
#
#  index_services_on_brand_id        (brand_id)
#  index_services_on_device_type_id  (device_type_id)
#  index_services_on_user_id         (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (brand_id => brands.id)
#  fk_rails_...  (device_type_id => device_types.id)
#  fk_rails_...  (user_id => users.id)
#
class Service < ApplicationRecord
  audited
  belongs_to :device_type
  belongs_to :brand
  belongs_to :user
  belongs_to :customer

  validates :defect, presence: true
  validates :appointment_date, presence: true

  enum state: ['Bekliyor', 'Teslim edildi, tamamlandı', 'Müşteri Tarafından İptal', 'Bizim Tarafımızdan İptal', 'Tekrar', 'Atölyede, tamir ediliyor']


  after_initialize do |service|
    service.user = User.current
  end

  def display
    self.brand_name + " " + self.device_name
  end

  def brand_name
  	self.brand[:brand_name]
  end

  def device_name
  	self.device_type[:device_name]
  end

  def district_name
  	self.district[:discrict_name]
  end

  def get_status
  	Service.states.key(self.status.to_i)
  end

  def full_address
    self.address + " " + self.district_name
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_services, only: [:index, :list]
  protect_from_forgery except:[ :show, :new ]

  def show
    @deletable = "Servisi Sil"
    render_modal "Servis Detayı"
  end

  def new
    render_modal "Yeni Servis"
  end

  def create
    if @object.save
      flash[:success] = "Servis oluşturuldu"
      respond_to do |format|
        format.js { render "#{params[:action]}"}
        format.html { render "#{params[:action]}"}
      end
    else
      render partial: "errors"
    end
  end

  def update
    if @object.update(permit_params)
      flash[:success] = "Servis Güncellendi"
      respond_to do |format|
        format.js { render "#{params[:action]}" }
        format.html { render "#{params[:action]}"}
      end
    else
      render partial: "errors"
    end
  end

  def list
    render "list"
  end

  private

  def set_services
    @services = current_user.services.order(created_at: :asc)
  end
    # Only allow a list of trusted parameters through.
    def permit_params
      params.fetch(:service, {}).permit(:name, :phone, :address, :district_id, :device_type_id, :brand_id, :defect, :description, :appointment_date, :subcontractor, :customer_id, :subcontractor_id, :status)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/partials/_form.html.erb
<div class="ui form">
  <%= simple_form_for @object, remote: true, html: { id: dom_id(@object, params[:action]) } do |f| %>
    <h4 class="ui dividing header">Müşterinin</h4>

    <% unless @object.new_record? %>
    <div class="ui cards">
      <div class="card">
        <div class="content">
          <div class="header">
            <%= link_to @object.customer.name.capitalize, customer_path(@object.customer), remote: true %>
          </div>
          <div class="meta">
            Servis <%= time_ago_in_words @object.created_at %> önce kaydedilmiş
          </div>

          <div class="description">
            Telefon: <%= @object.customer.phone %> <br>
            Adres: <%= @object.customer.full_address %>
          </div>
        </div>
      </div>
    </div>
    <div class="ui hidden divider"></div>
      <%= f.hidden_field :customer_id, value: @object.customer.id %>
    <% end %>

    <% if @object.new_record? %>
    <div class="field">
      <div class="two fields">
        <%= f.association :customer, input_html: { class: 'ui selection dropdown field search customer_list' }, wrapper_html: { class: 'field' } %>
      </div>
    </div>
    <% end %>

    <% if @object.address.present? %>
    <div class="field">
      <div class="two fields">
        <%= f.input :address, as: :text, label: 'Adres', required: true, placeholder: "Adres", readonly: true, input_html: { rows: "2" }, wrapper_html: {class: 'eight wide field'} %>
      </div>
    </div>
    <% end %>

    <div class="field">
      <div class="two fields">
        <%= f.input :status, label: 'Durum', collection: Service.states.map { |state| state }, input_html: { class: 'ui selection dropdown field' }, wrapper_html: { class: 'field' } %>
      </div>
    </div>

    <div class="field">
      <div class="two fields">
        <%= f.association :device_type, label: 'Cihaz Tipi', :collection => DeviceType.all.map { |e| [e.device_name, e.id] }, input_html: { class: 'ui selection dropdown field search' }, wrapper_html: { class: 'field' }, include_blank: false %>
        <%= f.association :brand, label: 'Marka', :collection => Brand.all.map { |e| [e.brand_name, e.id] }, input_html: { class: 'ui selection dropdown field search' }, wrapper_html: { class: 'field' }, include_blank: false %>
      </div>
    </div>

    <div class="field">
      <div class="two fields">
        <%= f.input :defect, as: :text, label: 'Arıza Açıklaması', placeholder: "Arıza", input_html: { rows: "2" }, wrapper_html: {class: 'field'} %>
        <%= f.input :description, as: :text, label: 'Servis Notu', placeholder: "Müşteri ile ilgili açıklama", input_html: { class: "field", rows: "2" }, wrapper_html: {class: 'field'} %>
      </div>
    </div>

    <div class="field">
      <div class="two fields">
        <div class="field">
          <div class="ui calendar" id="calendar">
            <label class="text optional">Gidilecek Tarih</label>
            <%= f.input :appointment_dates, wrapper_html: {class: 'ui left icon'}, label: false do %>
              <i class="calendar icon"></i>
              <%= f.input_field :appointment_date, as: :string, placeholder: 'Gidilecek Tarih', autocomplete: "off" %>
            <% end %>
          </div>
        </div>

        <div class="field">
          <label class="text optional">Taşeron</label>
          <%= f.select :subcontractor_id, options_for_select(current_user.subcontractors.map { |s| ["#{s.name} - #{s.credit}", s.id] }, selected: ( f.object.subcontractor_id rescue false )), include_blank: 'Taşeron Yok', class: 'ui dropdown field' %>
        </div>

      </div>
    </div>

  <% end %>
</div>

<script type="text/javascript" charset="utf-8">
    $('select.dropdown.customer_list').dropdown({
        apiSettings: {
            // this url parses query server side and returns filtered results
            url: "<%= customer_list_data_path(:json) %>?q={query}",
            cache: false
        },
        allowReselection: true,
        message: {
            noResults: '<%= link_to 'Yeni müşteri ekle', new_customer_path(from: 'services_list', close_modal: dom_class(@object)), remote: true %>'
        }
    });
</script>

app/views/services/partials/_service_list.html.erb
<table class="ui celled table" id="service_table">
  <thead>
  <tr>
    <th>Ad Soyad</th>
    <th>Semt</th>
    <th>Marka</th>
    <th>Cihaz Tipi</th>
    <th>Durumu</th>
  </tr>
  </thead>

  <tbody>
  <% @services.each do |service| %>
    <tr>
      <td><%= link_to service.customer.name, service, remote: true %></td>
      <td><%= service.customer.district_name %></td>
      <td><%= service.brand_name %></td>
      <td><%= service.device_name %></td>
      <td><%= service.get_status %></td>
    </tr>
  <% end %>
  </tbody>

  <tfoot class="full-width">
  <tr>
    <th colspan="5">
      <%= link_to new_service_path, remote: true, class: 'ui right floated small primary labeled icon button new_service' do %>
        <i class="plus icon"></i> Servis Ekle
      <% end %>
    </th>
  </tr>
  </tfoot>
</table>